name : demo-actions
on : [push, pull_request]

jobs:

  my_first_job:
    name: San Luis
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - run:  uname -a
      - run: echo " ====== Say Hello from San Luis =========="
      
      
  my_second_job:
    name: Jardin
    runs-on: ubuntu-latest
    steps:
      - run: echo "<<<<<< Say Hello from Jardi >>>>>>>"


      
  my_third_job:
    name: Rio Claro
    runs-on: ubuntu-latest
    steps:
      - run: echo "~~~~~~~ Say Hello from Rio Claro ~~~~~~~~~"
